### ISSUE TITLE
Implement an If Else parser

### ISSUE THREAD

**Issue by JerryNyoike** [JerryNyoike/upgraded-winner#1]

**Comment by JerryNyoike** [comment]
@Pancakem As seen on the [lexical syntax](https://www.cs.kent.ac.uk/people/staff/dat/miranda/manual/26.html) there is no `if...else` but rather just an `if` statement which is used to create function guards.

**Comment by Pancakem** [comment]
Can we pair on this sometime?

**Comment by JerryNyoike** [comment]
@Pancakem I already started on this, the if parser works but I haven't yet handled the case when it is preceded by whitespace or whitespace comes after it. Perhaps we can pair on that?

**Comment by JerryNyoike** [comment]
@Pancakem I tried using [this](https://docs.rs/nom/7.1.0/nom/recipes/index.html#wrapper-combinators-that-eat-whitespace-before-and-after-a-parser) recipe for whitespace without any luck, I get an `Incomplete` error from nom.

**Comment by Pancakem** [comment]
> 

Do you know why you get the `Incomplete` error? @JerryNyoike
