### ISSUE TITLE
Implement parser to identify keywords

### ISSUE THREAD

**Issue by JerryNyoike** [JerryNyoike/upgraded-winner#2]

**Comment by Pancakem** [comment]
Hey @JerryNyoike. I think you had already implemented this feature?

```
let value = match parse_identifier("hello123_world'") {
            Ok((_, matched)) => match matched {
                MirandaIdentifier(x) => x,
                _ => panic!("Error"),
            },
            Err(_) => panic!("Could not parse identifier"),
        };

        assert_eq!(value, "hello123_world'".to_string());

```
We have this test passing. Do we need to achieve anything else?

**Comment by JerryNyoike** [comment]
@Pancakem In the function you've linked I implemented a function to identify identifiers for functions and variable bindings. What we need to achieve in this issue, is a way to identify the languages keywords.

**Comment by Pancakem** [comment]
@Pancakem I overlooked that. Thanks!
